### ISSUE TITLE
tests fail with __getitem__() missing 1 required positional argument: 'user_charset'

### ISSUE THREAD

**Issue by raybellwaves** [pydap/pydap#224]
This was introduced in https://github.com/pydap/pydap/pull/223

e.g. running the test suite gives
```
============================================================== short test summary info ==============================================================
FAILED src/pydap/server/devel.py::pydap.server.devel.LocalTestServer
FAILED src/pydap/server/devel_ssl.py::pydap.server.devel_ssl.LocalTestServerSSL
FAILED src/pydap/tests/test_handlers_dap.py::TestDapHandler::test_grid - TypeError: __getitem__() missing 1 required positional argument: 'user_ch...
FAILED src/pydap/tests/test_handlers_dap.py::TestDapHandler::test_grid_erddap - TypeError: __getitem__() missing 1 required positional argument: '...
FAILED src/pydap/tests/test_handlers_dap.py::TestDapHandler::test_grid_erddap_output_grid_false - TypeError: __getitem__() missing 1 required posi...
FAILED src/pydap/tests/test_handlers_dap.py::TestDapHandler::test_grid_gzip - TypeError: __getitem__() missing 1 required positional argument: 'us...
FAILED src/pydap/tests/test_handlers_dap.py::TestDapHandler::test_grid_output_grid_false - TypeError: __getitem__() missing 1 required positional ...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxy::test_comparisons - TypeError: __getitem__() missing 1 required positional argument: 'u...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxy::test_getitem - TypeError: __getitem__() missing 1 required positional argument: 'user_...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxy::test_getitem_out_of_bound - TypeError: __getitem__() missing 1 required positional arg...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxy::test_inexact_division - TypeError: __getitem__() missing 1 required positional argumen...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxy::test_iteration - TypeError: __getitem__() missing 1 required positional argument: 'use...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxyShort::test_getitem - TypeError: __getitem__() missing 1 required positional argument: '...
FAILED src/pydap/tests/test_handlers_dap.py::TestBaseProxyString::test_getitem - TypeError: __getitem__() missing 1 required positional argument: ...
FAILED src/pydap/tests/test_handlers_dap.py::TestStringBaseType::test_getitem - TypeError: __getitem__() missing 1 required positional argument: '...
FAILED src/pydap/tests/test_handlers_dap.py::TestArrayStringBaseType::test_getitem - TypeError: __getitem__() missing 1 required positional argume...
FAILED src/pydap/tests/test_handlers_netcdf.py::test_open - TypeError: __getitem__() missing 1 required positional argument: 'user_charset'
FAILED src/pydap/tests/test_server_devel.py::test_netcdf - TypeError: cannot pickle '_thread.lock' object
FAILED src/pydap/tests/test_server_devel.py::test_timeout - TypeError: __getitem__() missing 1 required positional argument: 'user_charset'
FAILED src/pydap/tests/test_server_devel_ssl.py::test_open - requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=53776): ...
FAILED src/pydap/tests/test_server_devel_ssl.py::test_verify_open_url - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='0.0.0.0', p...
FAILED src/pydap/tests/test_special_chars.py::TestQuote::test_client - TypeError: __getitem__() missing 1 required positional argument: 'user_char...
FAILED src/pydap/tests/test_special_chars.py::TestPeriod::test_client - TypeError: __getitem__() missing 1 required positional argument: 'user_cha...
FAILED src/pydap/tests/test_wsgi_functions.py::TestDensity::test_projection - NameError: name 'gsw' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestDensity::test_selection - NameError: name 'gsw' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_default - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_grads_step - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_point - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_projection - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_selection_only - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_subset - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_functions.py::TestBounds::test_subset_with_selection - NameError: name 'coards' is not defined
FAILED src/pydap/tests/test_wsgi_ssf.py::TestMiddleware::test_selection - NameError: name 'gsw' is not defined
FAILED src/pydap/tests/test_wsgi_ssf.py::TestMiddleware::test_selection_no_comparison - NameError: name 'coards' is not defined
============================================== 34 failed, 341 passed, 8 skipped, 297 warnings in 8.83s ==============================================
```

There could be a smarter way to pass `user_charset` from `DAPHandler` to the functions with used to only take `r`
