### ISSUE TITLE
'<class 'pydap.model.BaseType'>' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by MBARIMike** [pydap/pydap#132]
I updated to Pydap==3.2.2 and my tests are failing with:

```
Traceback (most recent call last):
  File "/home/travis/build/stoqs/stoqs/stoqs/loaders/../loaders/__init__.py", line 797, in checkForValidData
    values = self.ds[v].array[:].flatten()
  File "/home/travis/miniconda3/lib/python3.6/site-packages/pydap/model.py", line 239, in __getattr__
    % (type(self), attr))
AttributeError: '<class 'pydap.model.BaseType'>' object has no attribute 'flatten'
```

It seems that Numpy's .flatten() method is no longer recognized.

**Comment by MBARIMike** [comment]
Running my tests with Pydap==3.2.1 I see that [this code](https://github.com/pydap/pydap/blob/4ae73e393b0d52bce9d1cf5571945a9ed884d526/src/pydap/model.py#L234-L239) is never reached with the `values = self.ds[v].array[:].flatten()` call. I wonder if [this commit](https://github.com/pydap/pydap/commit/4207286bc173dc9971eedd5508c41878e18cf1aa) changed how attributes are examined for GridType objects...

**Comment by MBARIMike** [comment]
It seems that previous versions of Pydap allowed accessing data without using the .data attribute. Here are [the specific changes](https://github.com/stoqs/stoqs/pull/659/commits/8839c32d2607ec3484b71efa5a85cdcc6fa87b38) to my code to make it work in version 3.2.2. 

This issue may be closed unless there is a desire/need to be backward compatible.
